# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unittest

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Lint with pycodestyle
      run: |
        pycodestyle armature --show-source --ignore E501
    - name: Test with coverage and unittest
      run: |
        "$C4DPY" -m unittest discover -v -s $PWD/tests -p "*_test.py"
